"""Wolf rig export (v0.14): the eight painted parts of each wolf (tools/art/v012/wolves.png), placed as in
the owner's reference assembly, pixelized at the game scale and saved as separate atlas frames, plus their
layout and pivots for the runtime rig (src/characters/WolfRig.js).

Usage: python3 tools/wolf_rig.py   → tools/raw/raw_wolf_<colour>_p_<part>.png, data/wolfRig.js
Then rebuild the atlas: python3 tools/build_sprites.py tools/raw assets/sprites
"""
import os, json, importlib.util, sys, types
import numpy as np
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# borrow the helpers of process_art5 without running its batch (the module body is cut before the batches)
src = open(os.path.join(ROOT, 'tools/process_art5.py')).read()
head = src.split('def save_portrait')[0]
wolf = src[src.index('# ---------------------------------------------------------------- wolves'):src.index('WOLVES = {')]
mod = types.ModuleType('pa5'); mod.__dict__['__file__'] = os.path.join(ROOT, 'tools/process_art5.py')
exec(head + '\n' + wolf, mod.__dict__)
RAW = mod.RAW

PARTS = ['hindR', 'frontR', 'tail', 'body', 'hindL', 'frontL', 'ruff', 'head']      # back to front
# pivots in the part image (fractions, x after mirroring so the wolf faces +x, y from the top):
PIVOT = {'head': (0.10, 0.70), 'ruff': (0.30, 0.12), 'tail': (0.86, 0.12), 'body': (0.18, 0.45),
         'frontL': (0.5, 0.06), 'frontR': (0.5, 0.06), 'hindL': (0.5, 0.06), 'hindR': (0.5, 0.06)}
WOLVES = {'grey': (0, 0), 'white': (mod.W2, 0), 'red': (0, mod.H2), 'dark': (mod.W2, mod.H2)}

rig = {}
for colour, q in WOLVES.items():
    stand = mod.compose(q, 'stand')
    lay = mod.placed(q)
    # the crop of the assembled standing wolf, in canvas px (compose crops to the alpha bbox)
    canvas = Image.new('RGBA', (1400, 1100))
    for key in mod.ORDER:
        im, x, y = lay[key]
        canvas.alpha_composite(im, (x, y))
    a = np.asarray(canvas)
    ys, xs = np.where(a[..., 3] > 20)
    x0, y0, x1, y1 = xs.min(), ys.min(), xs.max() + 1, ys.max() + 1
    S = 150 / stand.shape[0]
    Wc, Hc = (x1 - x0) * S, (y1 - y0) * S
    out = {'W': round(Wc, 1), 'H': round(Hc, 1), 'parts': {}}
    for key in PARTS:
        im, x, y = lay[key]
        arr = np.asarray(im).astype(np.float32)[:, ::-1]           # face +x like every sprite
        img = mod.pixelize(arr, S)
        name = f'wolf_{colour}_p_{key}'
        img.save(os.path.join(RAW, f'raw_{name}.png'))
        w, h = img.size
        left = Wc - (x - x0 + im.size[0]) * S                       # mirrored
        top = (y - y0) * S
        fx, fy = PIVOT[key]
        out['parts'][key] = dict(l=round(left, 1), t=round(top, 1), w=w, h=h, fx=fx, fy=fy)
    rig[colour] = out
    print(colour, out['W'], out['H'])

with open(os.path.join(ROOT, 'data/wolfRig.js'), 'w') as f:
    f.write('// Generated by tools/wolf_rig.py — layout (cm, from the top-left of the standing wolf, facing +x)\n')
    f.write('// and pivots (fractions of each part image) of the eight painted wolf parts.\n')
    f.write('export const WOLF_RIG = ' + json.dumps(rig, indent=1) + ';\n')
